# Generated by Django 6.0.2 on 2026-02-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_task_name_remove_task_status_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='task', max_length=200, verbose_name='Title'),
        ),
    ]
